# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
- name: Location
  value: 'westeurope'
- name: ResourceGroup
  value: 'RG-EUW-AIB'
- name: ImageTemplateName
  value: 'imageTemplateWin11Multi'

steps:
- task: AzureCLI@2
  displayName: "Copy Install Script"
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship 2 (8fdc4569-2133-492f-b048-7fbfff6b39d1)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload \
                        --account-name samemdroid \
                        --container-name avdimagebuilder \
                        --name Install-Applications_v2.ps1 \
                        --file Install-Applications_v2.ps1 \
- task: AzureResourceManagerTemplateDeployment@3
  displayName: "Deploy Template"
  continueOnError: true
  inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Microsoft Azure Sponsorship 2 (8fdc4569-2133-492f-b048-7fbfff6b39d1)'
      subscriptionId: '8fdc4569-2133-492f-b048-7fbfff6b39d1'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(ResourceGroup)'
      location: '$(Location)'
      templateLocation: 'Linked artifact'
      csmFile: 'Win11MultiTemplate_v2.json'
      csmParametersFile: 'Win11MultiTemplate_v2.parameters.json'
      deploymentMode: 'Incremental'
- task: AzurePowerShell@5
  displayName: "Install AZ.ImageBuilder"
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship 2 (8fdc4569-2133-492f-b048-7fbfff6b39d1)'
    ScriptType: 'InlineScript'
    Inline: 'Install-Module -name Az.ImageBuilder -AllowPrerelease -Force -Scope CurrentUser'
    azurePowerShellVersion: 'LatestVersion'
- task: AzurePowerShell@5
  displayName: "Build Image"
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship 2 (8fdc4569-2133-492f-b048-7fbfff6b39d1)'
    ScriptType: 'InlineScript'
    Inline: 'Start-AzImageBuilderTemplate -ResourceGroupName $(ResourceGroup) -Name $(ImageTemplateName)'
    azurePowerShellVersion: 'LatestVersion'
- task: AzurePowerShell@5
  displayName: "Remove Template"
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship 2 (8fdc4569-2133-492f-b048-7fbfff6b39d1)'
    ScriptType: 'InlineScript'
    Inline: 'Remove-AzImageBuilderTemplate -ImageTemplateName $(ImageTemplateName) -ResourceGroupName $(ResourceGroup)'
    azurePowerShellVersion: 'LatestVersion'
